
function insight(icon,title,text){return `<div class="insight"><div class="insight-icon">${icon[0]}</div><div><strong>${esc(title)}</strong><p>${esc(text)}</p></div></div>`}
function distributionHtml(values){const bands=[{l:'0–39',a:0,b:40},{l:'40–59',a:40,b:60},{l:'60–74',a:60,b:75},{l:'75–89',a:75,b:90},{l:'90–100',a:90,b:101}],counts=bands.map(x=>values.filter(v=>v>=x.a&&v<x.b).length),max=Math.max(1,...counts);return `<div class="distribution">${bands.map((x,i)=>{const height=Math.max(5,counts[i]/max*145),inside=height>=44;return `<div class="dist-col"><div class="dist-plot"><div class="dist-bar" style="height:${height}px"><b class="dist-value ${inside?'inside':'outside'}">${counts[i]}</b></div></div><span>${x.l}%</span></div>`}).join('')}</div>`}
function trendChartHtml(points,opts={}){if(!points.length)return `<p class="muted">Cadastre avaliações para acompanhar a evolução.</p>`;const count=points.length,large=opts.large===true,valueSize=large?(count<=3?31:count<=5?27:count<=8?23:20):(count<=3?24:count<=5?21:count<=8?18:16),labelSize=large?(count<=3?19:count<=5?17:count<=8?15:13):(count<=3?16:count<=5?14:count<=8?12.5:11),labelChars=large?(count<=3?17:count<=5?15:count<=8?12:10):(count<=3?22:count<=5?17:count<=8?13:10),w=820,h=272,padX=88,padTop=42,padBottom=56,min=0,max=100,usableH=h-padTop-padBottom,step=points.length>1?(w-padX*2)/(points.length-1):0,xy=points.map((p,i)=>({x:padX+i*step,y:padTop+(max-p.avg)/(max-min)*usableH,...p})),line=xy.map(p=>`${p.x},${p.y}`).join(' '),area=`M ${xy[0].x} ${h-padBottom} L ${line.replaceAll(' ', ' L ')} L ${xy.at(-1).x} ${h-padBottom} Z`;return `<svg class="svg-chart" style="--chart-value-size:${valueSize}px;--chart-label-size:${labelSize}px" viewBox="0 0 ${w} ${h}" role="img" aria-label="Evolução em percentual"><defs><linearGradient id="chartAreaGradient" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stop-color="#0f8588" stop-opacity=".24"></stop><stop offset="100%" stop-color="#2563eb" stop-opacity=".02"></stop></linearGradient></defs>${[0,25,50,75,100].map(v=>{const y=padTop+(100-v)/100*usableH;return `<line class="chart-grid" x1="${padX}" y1="${y}" x2="${w-padX}" y2="${y}"></line><text class="chart-label" x="8" y="${y+4}">${v}%</text>`}).join('')}<path class="chart-area" d="${area}"></path><polyline class="chart-line" points="${line}"></polyline>${xy.map((p,index)=>{const first=index===0,last=index===xy.length-1,labelX=first?8:last?w-8:p.x,labelAnchor=first?'start':last?'end':'middle',valueX=first?p.x+15:last?p.x-15:p.x,valueAnchor=first?'start':last?'end':'middle',valueY=Math.max(20,p.y-20);return `<circle class="chart-dot-halo" cx="${p.x}" cy="${p.y}" r="12"></circle><circle class="chart-dot" cx="${p.x}" cy="${p.y}" r="6"></circle><text class="chart-value" text-anchor="${valueAnchor}" x="${valueX}" y="${valueY}">${Math.round(p.avg)}%</text><text class="chart-label" text-anchor="${labelAnchor}" x="${labelX}" y="${h-14}">${esc(shortName(p.name,labelChars))}</text>`}).join('')}</svg>`}
function hardQuestionsTable(batch,n){const stats=aggregateQuestionStats(batch).sort((a,b)=>a.correctRate-b.correctRate).slice(0,n);return questionListHtml(stats)}
function questionInsights(stats){const hardest=stats.slice().sort((a,b)=>a.correctRate-b.correctRate).slice(0,3),mostBlank=stats.slice().sort((a,b)=>b.blankRate-a.blankRate).slice(0,2),mostMulti=stats.slice().sort((a,b)=>b.multiRate-a.multiRate).slice(0,2);let html=''; hardest.forEach(q=>{const section=sectionForQuestion(q.q)?.name||'Não mapeada';html+=insight('Q',`Revisar Q${q.q} - ${section}`,`A questão teve ${fmtPct(q.correctRate)} de acerto. A alternativa correta é ${q.correctKey||'—'} e o distrator mais escolhido foi ${q.commonDistractor||'—'}.`)}); mostBlank.forEach(q=>{const section=sectionForQuestion(q.q)?.name||'Não mapeada',count=Math.round((q.total||0)*(q.blankRate||0)/100);html+=insight('B',`Brancos em Q${q.q} - ${section}`,`${count} aluno(s) deixaram a questão sem marcação. Verifique tempo, leitura do enunciado e segurança dos alunos.`)}); mostMulti.forEach(q=>{const section=sectionForQuestion(q.q)?.name||'Não mapeada',count=Math.round((q.total||0)*(q.multiRate||0)/100);html+=insight('M',`Múltiplas em Q${q.q} - ${section}`,`${count} aluno(s) fizeram marcação múltipla nesta questão.`)}); return html||'<p class="muted">Sem dados suficientes.</p>'}
function questionListHtml(stats){return stats.length?`<div class="table-wrap"><table class="table"><thead><tr><th>Item</th><th>Disciplina</th><th class="num">Acerto</th><th class="num">Em branco</th><th class="num">Múltiplas</th></tr></thead><tbody>${stats.map(q=>`<tr><td><b>Q${q.q}</b></td><td>${esc(sectionForQuestion(q.q)?.name||'Não mapeada')}</td><td class="num">${fmtPct(q.correctRate)}</td><td class="num">${Math.round((q.total||0)*(q.blankRate||0)/100)}</td><td class="num">${Math.round((q.total||0)*(q.multiRate||0)/100)}</td></tr>`).join('')}</tbody></table></div>`:'<p class="muted">Sem questões válidas.</p>'}
function attentionTable(list){return list.length?`<div class="table-wrap"><table class="table"><thead><tr><th>Aluno</th><th class="num">Atual</th><th class="num">Evolução</th><th>Motivo</th></tr></thead><tbody>${list.slice(0,12).map(x=>`<tr data-student="${esc(studentKey(x.student))}"><td><b>${esc(x.student.name)}</b><br><span class="muted">Nº ${esc(x.student.roll)}</span></td><td class="num">${fmtPct(percent(x.student))}</td><td class="num">${x.evolution==null?'—':deltaHtml(x.evolution)}</td><td>${esc(x.reasons.join(' · '))}</td></tr>`).join('')}</tbody></table></div>`:'<p class="muted">Nenhum caso prioritário pelas regras atuais.</p>'}
function summaryHtml(summary,priorities){return `${insight('D','Destaques',summary.strengths.length?summary.strengths.join(', '):'Ainda não há evidência suficiente para definir um ponto forte consolidado.')}${insight('F','Próximo foco',summary.focus.length?summary.focus.join(', '):'Manter o estudo equilibrado e revisar os erros da avaliação.')}${insight('A','Ação',priorities.length?`Refazer ${priorities.slice(0,4).map(q=>'Q'+q.q).join(', ')} e registrar por que a alternativa correta é a melhor resposta.`:'Revisar os itens errados e explicar pelo menos uma correção com as próprias palavras.')}${summary.collective.length?insight('T','Desafio da turma',`As questões ${summary.collective.slice(0,4).map(q=>'Q'+q).join(', ')} foram difíceis para muitos alunos e merecem retomada coletiva.`):''}`}
function priorityTable(list){return list.length?`<div class="table-wrap"><table class="table"><thead><tr><th>Questão</th><th>Disciplina</th><th class="num">Turma acertou</th><th>Por que priorizar</th></tr></thead><tbody>${list.slice(0,8).map(q=>`<tr><td><b>Q${q.q}</b></td><td>${esc(q.section?.name||'Não mapeada')}</td><td class="num">${fmtPct(q.classRate)}</td><td>${esc(q.reason)}</td></tr>`).join('')}</tbody></table></div>`:'<p class="muted">Nenhuma questão prioritária foi identificada.</p>'}
function studentTrajectoryPoints(student){const points=[];trajectoryDisplayBatches().forEach(b=>{const m=b.id===activeBatch()?.id?student:findHistoricalStudent(student,b);if(m)points.push({name:b.name,avg:percent(m),score:m.totalMarks,correct:m.correct,total:m.questionCount,batch:b})});return points}
function classTrajectoryPoints(className){return trajectoryDisplayBatches().map(b=>{const cls=b.classes.find(c=>classEquivalent(c.name,className));return cls?{name:b.name,avg:mean(cls.students.map(percent)),count:cls.students.length,batch:b}:null}).filter(Boolean)}
function classComponentHistoryBarsHtml(className){const batches=trajectoryDisplayBatches(),currentBatch=activeBatch(),components=state.sections.filter(s=>s.enabled).sort((a,b)=>+a.start-+b.start),rows=components.map(sec=>{const values=batches.map(batch=>{const cls=batch.classes.find(c=>classEquivalent(c.name,className));if(!cls)return null;const data=sectionAggregateForStudents(cls.students,sec);return data.total?{name:batch.name,value:data.percent,current:batch.id===currentBatch?.id}:null}).filter(Boolean);return values.length?{sec,values}:null}).filter(Boolean);if(!rows.length)return '<p class="muted">Não há avaliações comparáveis por componente para esta turma.</p>';return `<div class="history-component-chart">${rows.map(row=>{const current=row.values.find(v=>v.current)||row.values.at(-1),previous=row.values.filter(v=>!v.current).at(-1),diff=previous?current.value-previous.value:null;return `<div class="history-component-row"><div class="history-component-name">${esc(row.sec.name)}</div><div class="history-component-bars">${row.values.map(v=>`<div class="history-component-line ${v.current?'current':'previous'}"><span>${esc(shortName(v.name,14))}</span><div class="history-component-track"><div class="history-component-fill" style="width:${clamp(v.value,0,100)}%"></div></div><b>${fmtPct(v.value)}</b></div>`).join('')}</div><div class="history-component-delta">${diff==null?'—':deltaHtml(diff)}</div></div>`}).join('')}</div>`}
function sectionComparisonTableHtml(rows,emptyText='Não há comparação anterior disponível por componente.'){return rows.length?`<div class="table-wrap" style="margin-top:14px"><table class="table"><thead><tr><th>Componente</th><th class="num">Atual</th><th class="num">Anterior</th><th class="num">Variação</th></tr></thead><tbody>${rows.map(r=>`<tr><td><b>${esc(r.name)}</b></td><td class="num">${fmtPct(r.current)}</td><td class="num">${r.previous==null?'—':fmtPct(r.previous)}</td><td class="num">${r.previous==null?'—':deltaHtml(r.diff)}</td></tr>`).join('')}</tbody></table></div>`:`<p class="muted" style="margin-top:12px">${emptyText}</p>`}
function studentSectionChangeRows(student){const prev=findHistoricalStudent(student,primaryComparisonBatch());if(!prev)return[];return state.sections.filter(s=>s.enabled).sort((a,b)=>+a.start-+b.start).map(sec=>{const current=componentStudentPercent(student,sec),previous=componentStudentPercent(prev,sec);if(current==null&&previous==null)return null;return{name:sec.name,current:current??0,previous,diff:(current??0)-(previous??0)}}).filter(Boolean)}

function studentTrendDetailHtml(student){return `${trendChartHtml(studentTrajectoryPoints(student))}<div class="panel-sub" style="margin-top:10px">Por componente entre a avaliação atual e a anterior relacionada.</div>${sectionComparisonTableHtml(studentSectionChangeRows(student),'Não foi encontrada uma avaliação anterior relacionada para comparar os componentes do aluno.')}`}


function reportPreviewHtml(s,areas,summary,prev){const top=areas.slice().sort((a,b)=>b.percent-a.percent).slice(0,4),points=studentTrajectoryPoints(s),trajectoryDelta=points.length>1?points.at(-1).avg-points[0].avg:null,evo=state.comparisonMode==='trajectory'?trajectoryDelta:(prev?percent(s)-percent(prev):null),evoLabel=state.comparisonMode==='trajectory'?'TRAJETÓRIA':'EVOLUÇÃO';return `<div class="report-preview"><div class="report-title">MEU DESEMPENHO</div><div class="report-kpis"><div><b>${Math.round(percent(s))}%</b><span>APROVEITAMENTO</span></div><div><b>${evo===null?'—':fmtSigned(evo)+' pontos percentuais'}</b><span>${evoLabel}</span></div><div><b>${s.correct}/${s.questionCount}</b><span>ACERTOS</span></div></div>${top.map(a=>`<div class="report-bar"><b>${esc(shortName(a.name,16))}</b><i style="width:${clamp(a.percent,3,100)}%"></i><span>${Math.round(a.percent)}%</span></div>`).join('')}<div class="report-note"><b>DESTAQUE:</b> ${esc(summary.strengths.join(', ')||'resultado em desenvolvimento')}<br><b>PRÓXIMO FOCO:</b> ${esc(summary.focus.join(', ')||'revisão dos itens errados')}<br><b>AÇÃO:</b> refaça as questões indicadas e registre uma dúvida para discutir em aula.</div></div>`}
function questionTag(q){if(q.correctRate<35)return '<span class="tag bad">Retomada coletiva</span>';if(q.discrimination<5&&q.correctRate<80)return '<span class="tag warn">Revisar item</span>';if(q.blankRate>10)return '<span class="tag warn">Muitos brancos</span>';if(q.correctRate>85)return '<span class="tag good">Domínio amplo</span>';return '<span class="tag info">Acompanhar</span>'}

class ReportMiniPDF{
  constructor(){this.pageWidth=210;this.pageHeight=297;this.pages=[[]];this.pageIndex=0;this.fontName='helvetica';this.fontStyle='normal';this.fontSize=10;this.fill=[0,0,0];this.stroke=[0,0,0];this.textColor=[0,0,0];this.lineWidth=.2;this.lastAutoTable={finalY:0};}
  _cmd(s){this.pages[this.pageIndex].push(s)}
  _n(v){return Number(v).toFixed(3).replace(/\.000$/,'')}
  _pt(mm){return mm*72/25.4}
  _x(mm){return this._n(this._pt(mm))}
  _y(mm){return this._n(this._pt(this.pageHeight-mm))}
  _rgb(c){return c.map(v=>this._n((+v||0)/255)).join(' ')}
  addPage(){this.pages.push([]);this.pageIndex=this.pages.length-1;return this}
  setPage(n){this.pageIndex=Math.max(0,Math.min(this.pages.length-1,(+n||1)-1));return this}
  getNumberOfPages(){return this.pages.length}
  setFillColor(r,g,b){this.fill=[r,g??r,b??r];return this}
  setDrawColor(r,g,b){this.stroke=[r,g??r,b??r];return this}
  setTextColor(r,g,b){this.textColor=[r,g??r,b??r];return this}
  setLineWidth(v){this.lineWidth=+v||.2;return this}
  setFont(name='helvetica',style='normal'){this.fontName=name;this.fontStyle=style;return this}
  setFontSize(v){this.fontSize=+v||10;return this}
  _fontRef(){return this.fontStyle==='bold'?'F2':'F1'}
  _textWidth(text,size=this.fontSize){const factor=this.fontStyle==='bold'?.555:.515;return String(text??'').length*size*.3527778*factor}
  splitTextToSize(text,maxWidth){const paragraphs=String(text??'').split(/\n/),out=[];paragraphs.forEach(par=>{const words=par.split(/\s+/).filter(Boolean);if(!words.length){out.push('');return}let line='';words.forEach(word=>{const test=line?line+' '+word:word;if(this._textWidth(test)<=maxWidth)line=test;else{if(line)out.push(line);if(this._textWidth(word)<=maxWidth)line=word;else{let part='';for(const ch of word){if(this._textWidth(part+ch)>maxWidth&&part){out.push(part);part=ch}else part+=ch}line=part}}});if(line)out.push(line)});return out}
  _encodeText(text){const map={'€':128,'‚':130,'ƒ':131,'„':132,'…':133,'†':134,'‡':135,'ˆ':136,'‰':137,'Š':138,'‹':139,'Œ':140,'Ž':142,'‘':145,'’':146,'“':147,'”':148,'•':149,'–':150,'—':151,'˜':152,'™':153,'š':154,'›':155,'œ':156,'ž':158,'Ÿ':159};let out='';for(const ch of String(text??'')){let code=ch.charCodeAt(0);if(map[ch]!=null)code=map[ch];else if(code>255)code=63;const c=String.fromCharCode(code);out+=c==='\\'?'\\\\':c==='('? '\\(':c===')'?'\\)':c}return out}
  text(text,x,y,options={}){const lines=Array.isArray(text)?text:String(text??'').split(/\n/),lineMm=this.fontSize*.3527778*1.18;lines.forEach((line,i)=>{let xx=+x||0;const width=this._textWidth(line);if(options.align==='center')xx-=width/2;else if(options.align==='right')xx-=width;const yy=(+y||0)+i*lineMm;this._cmd(`BT /${this._fontRef()} ${this._n(this.fontSize)} Tf ${this._rgb(this.textColor)} rg 1 0 0 1 ${this._x(xx)} ${this._y(yy)} Tm (${this._encodeText(line)}) Tj ET`)});return this}
  line(x1,y1,x2,y2){this._cmd(`${this._rgb(this.stroke)} RG ${this._n(this._pt(this.lineWidth))} w ${this._x(x1)} ${this._y(y1)} m ${this._x(x2)} ${this._y(y2)} l S`);return this}
  rect(x,y,w,h,style='S'){const op=style==='F'?'f':style==='FD'||style==='DF'?'B':'S',yy=this.pageHeight-y-h;this._cmd(`${this._rgb(this.fill)} rg ${this._rgb(this.stroke)} RG ${this._n(this._pt(this.lineWidth))} w ${this._x(x)} ${this._x(yy)} ${this._x(w)} ${this._x(h)} re ${op}`);return this}
  roundedRect(x,y,w,h,rx,ry,style='S'){return this.rect(x,y,w,h,style)}
  circle(x,y,r,style='S'){const k=.5522847498,px=this._pt(x),py=this._pt(this.pageHeight-y),pr=this._pt(r),op=style==='F'?'f':style==='FD'||style==='DF'?'B':'S';this._cmd(`${this._rgb(this.fill)} rg ${this._rgb(this.stroke)} RG ${this._n(this._pt(this.lineWidth))} w ${this._n(px+pr)} ${this._n(py)} m ${this._n(px+pr)} ${this._n(py+k*pr)} ${this._n(px+k*pr)} ${this._n(py+pr)} ${this._n(px)} ${this._n(py+pr)} c ${this._n(px-k*pr)} ${this._n(py+pr)} ${this._n(px-pr)} ${this._n(py+k*pr)} ${this._n(px-pr)} ${this._n(py)} c ${this._n(px-pr)} ${this._n(py-k*pr)} ${this._n(px-k*pr)} ${this._n(py-pr)} ${this._n(px)} ${this._n(py-pr)} c ${this._n(px+k*pr)} ${this._n(py-pr)} ${this._n(px+pr)} ${this._n(py-k*pr)} ${this._n(px+pr)} ${this._n(py)} c ${op}`);return this}
  autoTable(opts={}){const left=opts.margin?.left??5,right=opts.margin?.right??5,bottom=opts.margin?.bottom??10,head=(opts.head?.[0]||[]).map(String),body=(opts.body||[]).map(row=>row.map(v=>String(v??''))),available=this.pageWidth-left-right,styles=opts.styles||{},fontSize=styles.fontSize||7,pad=styles.cellPadding||1.3,lineH=fontSize*.3527778*1.22,columnStyles=opts.columnStyles||{};let widths=head.map((_,i)=>+columnStyles[i]?.cellWidth||0),fixed=widths.reduce((a,b)=>a+b,0),flex=widths.filter(w=>!w).length||1,remaining=Math.max(20,available-fixed);widths=widths.map(w=>w||remaining/flex);let y=opts.startY||10;const drawRow=(cells,isHead,rowIndex)=>{const wrapped=cells.map((cell,i)=>this.splitTextToSize(cell,Math.max(4,widths[i]-pad*2))),height=Math.max(...wrapped.map(lines=>Math.max(1,lines.length)))*lineH+pad*2;if(y+height>this.pageHeight-bottom){this.addPage();y=10;if(!isHead)drawRow(head,true,-1)}const fill=isHead?(opts.headStyles?.fillColor||[232,244,247]):(rowIndex%2&&opts.alternateRowStyles?.fillColor?opts.alternateRowStyles.fillColor:[255,255,255]);let x=left;cells.forEach((cell,i)=>{this.setFillColor(...fill);this.setDrawColor(...(styles.lineColor||[214,226,232]));this.setLineWidth(styles.lineWidth||.15);this.rect(x,y,widths[i],height,'FD');this.setFont('helvetica',isHead?'bold':'normal');this.setFontSize(fontSize);this.setTextColor(...(isHead?(opts.headStyles?.textColor||[15,23,42]):(styles.textColor||[15,23,42])));this.text(wrapped[i],x+pad,y+pad+fontSize*.3527778*.85);x+=widths[i]});y+=height};drawRow(head,true,-1);body.forEach((row,i)=>drawRow(row,false,i));this.lastAutoTable={finalY:y};return this}
  _toBinary(){const objects=[];const add=s=>{objects.push(s);return objects.length};const catalogId=add(''),pagesId=add(''),font1Id=add('<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica /Encoding /WinAnsiEncoding >>'),font2Id=add('<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica-Bold /Encoding /WinAnsiEncoding >>'),pageIds=[];this.pages.forEach(commands=>{const stream=commands.join('\n'),contentId=add(`<< /Length ${stream.length} >>\nstream\n${stream}\nendstream`),pageId=add(`<< /Type /Page /Parent ${pagesId} 0 R /MediaBox [0 0 ${this._n(this._pt(this.pageWidth))} ${this._n(this._pt(this.pageHeight))}] /Resources << /Font << /F1 ${font1Id} 0 R /F2 ${font2Id} 0 R >> >> /Contents ${contentId} 0 R >>`);pageIds.push(pageId)});objects[catalogId-1]=`<< /Type /Catalog /Pages ${pagesId} 0 R >>`;objects[pagesId-1]=`<< /Type /Pages /Kids [${pageIds.map(id=>`${id} 0 R`).join(' ')}] /Count ${pageIds.length} >>`;let pdf='%PDF-1.4\n%âãÏÓ\n',offsets=[0];objects.forEach((obj,i)=>{offsets.push(pdf.length);pdf+=`${i+1} 0 obj\n${obj}\nendobj\n`});const xref=pdf.length;pdf+=`xref\n0 ${objects.length+1}\n0000000000 65535 f \n`;for(let i=1;i<=objects.length;i++)pdf+=`${String(offsets[i]).padStart(10,'0')} 00000 n \n`;pdf+=`trailer\n<< /Size ${objects.length+1} /Root ${catalogId} 0 R >>\nstartxref\n${xref}\n%%EOF`;return Uint8Array.from(pdf,c=>c.charCodeAt(0)&255)}
  save(filename){const blob=new Blob([this._toBinary()],{type:'application/pdf'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=filename||'relatorio.pdf';document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1500)}
}